apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: billpay-templates
  description: BillPay Backstage Templates
  annotations:
    backstage.io/managed-by-location: url:https://github.com/giovanemere/templates_backstage/blob/main/catalog-info.yaml
spec:
  targets:
    - ./billpay-complete-stack/template.yaml
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: billpay-platform
  title: BillPay Platform
  description: Sistema completo de pagos enterprise con microservicios
spec:
  owner: platform-team
